<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SetsTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('sets')->delete();
        DB::table('sets')->insert(array(
            0 => array(
                'active' => 1,
                'promo' => 1,
                'setorder' => 1,
                'released' => '2017-03-09 03:51:05',
                'title' => 'Zauberwesen Pokes Around The World',
                'setlength' => 75,
                'bpm' => 121,
                'filename' => 'zauberwesen_pokes_around_the_world.mp3',
                'filetype' => 'mp3',
                'cover' => 'zauberwesen.jpg',
                'description' => 'Begleite das Zauberwesen auf seiner Reise um die Welt. Es kennt viele geheimnisvolle Orte. Manche kann man nicht so einfach anschauen - aber hören und wer richtig zuhören kann, dem wird sie das Zauberwesen sichtbar machen.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            1 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2016-10-07 03:51:05',
                'title' => 'Sie Kamen Aus Rackzoohm',
                'setlength' => 85,
                'bpm' => 123,
                'filename' => 'sie_kamen_aus_rackzoohm.mp3',
                'filetype' => 'mp3',
                'cover' => 'rackzoohm.jpg',
                'description' => 'Der Text ist hier.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            2 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2018-11-24 03:51:05',
                'title' => 'NaturalSelection',
                'setlength' => 73,
                'bpm' => 125,
                'filename' => 'naturalselection.mp3',
                'filetype' => 'mp3',
                'cover' => 'naturalselection.jpg',
                'description' => 'Ich atme tief ein. Scheint Freiheit zu sein.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            3 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2016-02-05 03:51:05',
                'title' => 'Liquid Session In Hamburg I',
                'setlength' => 97,
                'bpm' => 123,
                'filename' => 'liquid_session_in_hamburg_01.mp3',
                'filetype' => 'mp3',
                'cover' => 'liquid1.jpg',
                'description' => 'Der erste Streich in Hamburg.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            4 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2016-02-09 03:51:05',
                'title' => 'Liquid Session In Hamburg II',
                'setlength' => 75,
                'bpm' => 120,
                'filename' => 'liquid_session_in_hamburg_02.mp3',
                'filetype' => 'mp3',
                'cover' => 'liquid2.jpg',
                'description' => 'Und der zweite folgt zu gleich.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            5 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2017-01-04 03:51:05',
                'title' => 'Keine Bademeister Bitte!',
                'setlength' => 75,
                'bpm' => 122,
                'filename' => 'keine_bademeister_bitte.mp3',
                'filetype' => 'mp3',
                'cover' => 'bademeister.jpg',
                'description' => 'Titel ist ernst zu nehmen, ihr werdet es hassen :)',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            6 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2017-07-11 03:51:05',
                'title' => 'Dubno',
                'setlength' => 73,
                'bpm' => 122,
                'filename' => 'dubno.mp3',
                'filetype' => 'mp3',
                'cover' => 'dubno.jpg',
                'description' => 'Einer nannte seinen Sound mal Schneckno, da kam mir Duno in dem Kopf.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            7 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2017-07-11 03:51:05',
                'title' => 'Autophan',
                'setlength' => 53,
                'bpm' => 122,
                'filename' => 'autophan.mp3',
                'filetype' => 'mp3',
                'cover' => 'autophan.jpg',
                'description' => 'Verliere jedes Gefühl für Zeit. Ein Lächeln rast vorbei. Von Bergen eingerahmt.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            8 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2015-01-02 03:51:05',
                'title' => 'Waves Becoming Landmarks',
                'setlength' => 78,
                'bpm' => 101,
                'filename' => 'waves_becoming_landmarks.mp3',
                'filetype' => 'mp3',
                'cover' => 'landmark.jpg',
                'description' => 'Musik schwingt immer gleich, im Kopf erhält sie erst ihre ganz persönliche Gestalt.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
            9 => array(
                'active' => 1,
                'promo' => 0,
                'setorder' => 1,
                'released' => '2018-01-11 03:51:05',
                'title' => 'Etwas Herzblut Gereicht',
                'setlength' => 114,
                'bpm' => 123,
                'filename' => 'etwas_herzblut_gereicht.mp3',
                'filetype' => 'mp3',
                'cover' => 'herzblut.jpg',
                'description' => 'Derjenige der mein Herzblut auf der Tanzfläche fließen sehen will, der spielet bitte doch solche Musik.',
                'created_at' => '2017-09-09 03:51:05',
                'updated_at' => '2017-09-09 03:51:05',
            ),
        ));
    }
}
